NKUST109-2/Controllers/ChatroomController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using NKUST109_2.Data;
using NKUST109_2.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Threading;
using System.Threading.Tasks;

namespace NKUST109_2
{
    [Authorize]
    public class ChatroomController : Controller
    {
        private readonly ApplicationDbContext dbContext;

        public ChatroomController(ApplicationDbContext dbContext)
        {
            this.dbContext = dbContext;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public IActionResult FetchMessage(int fromIndex, int longPollSec)
        {
            var messageQuery = dbContext.ChatMessage;
            DateTime endTime = DateTime.Now.AddSeconds(longPollSec);
            while (DateTime.Now.CompareTo(endTime) < 0)
            {
                if (messageQuery.Any())
                {
                    int latestMessageIndex = messageQuery.OrderBy(message => message.Id).Last().Id;
                    if (latestMessageIndex >= fromIndex)
                    {
                        IQueryable<Message> messages = messageQuery.Where(message => message.Id >= fromIndex);
                        return Json(messages);
                    }
                }
                Thread.Sleep(300);
            }
            return StatusCode(StatusCodes.Status408RequestTimeout);
        }

        [HttpPost]
        public IActionResult SendMessage(string msg)
        {
            if (msg == "")
            {
                return StatusCode(StatusCodes.Status400BadRequest);
            }
            Message message = new Message()
            {
                Content = msg,
                Author = HttpContext.User.Identity.Name.Split("@")[0],
                Timestamp = DateTime.Now
            };
            EntityEntry<Message> entity = dbContext.ChatMessage.Add(message);
            dbContext.SaveChanges();
            int latestId = entity.Entity.Id;
            return Json(latestId);
        }
    }
}

NKUST109-2/Controllers/VolumeDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using KHLightTrail;
using NKUST109_2.Data;

namespace NKUST109_2.Controllers
{
    public class VolumeDataController : Controller
    {
        private readonly ApplicationDbContext _context;

        public VolumeDataController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: VolumeDatas
        public async Task<IActionResult> Index(int? year)
        {
            List<VolumeData> volumeData;
            if (year == null)
            {
                volumeData = await _context.VolumeData.ToListAsync();
            }
            else
            {
                ViewData["year"] = year;
                volumeData = _context.VolumeData.Where(volumeData => volumeData.Year == year).ToList();
            }
            return View(volumeData);
        }

        // GET: VolumeDatas/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volumeData = await _context.VolumeData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (volumeData == null)
            {
                return NotFound();
            }

            return View(volumeData);
        }

        // GET: VolumeDatas/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: VolumeDatas/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Year,Month,TotalVolume,AverangeDailyVolume,AvgHolidayVolume,AvgBuyTicketWithCardOnPlatform,AvgBuyTicketWithCardOnTrain,AvgBuyTicketFromTicketMachine,AvgRebuyTicket,AvgBuyGroupTicket,AvgBuyTicketByManual,Remark")] VolumeData volumeData)
        {
            if (ModelState.IsValid)
            {
                _context.Add(volumeData);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(volumeData);
        }

        // GET: VolumeDatas/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volumeData = await _context.VolumeData.FindAsync(id);
            if (volumeData == null)
            {
                return NotFound();
            }
            return View(volumeData);
        }

        // POST: VolumeDatas/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Year,Month,TotalVolume,AverangeDailyVolume,AvgHolidayVolume,AvgBuyTicketWithCardOnPlatform,AvgBuyTicketWithCardOnTrain,AvgBuyTicketFromTicketMachine,AvgRebuyTicket,AvgBuyGroupTicket,AvgBuyTicketByManual,Remark")] VolumeData volumeData)
        {
            if (id != volumeData.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(volumeData);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VolumeDataExists(volumeData.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(volumeData);
        }

        // GET: VolumeDatas/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var volumeData = await _context.VolumeData
                .FirstOrDefaultAsync(m => m.Id == id);
            if (volumeData == null)
            {
                return NotFound();
            }

            return View(volumeData);
        }

        // POST: VolumeDatas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var volumeData = await _context.VolumeData.FindAsync(id);
            _context.VolumeData.Remove(volumeData);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool VolumeDataExists(int id)
        {
            return _context.VolumeData.Any(e => e.Id == id);
        }

        public async Task<IActionResult> ImportFromOfficial()
        {
            List<VolumeData> newVolumeDatas = await VolumeDataset.GetAllVolumes();
            newVolumeDatas.ForEach(data =>
            {
                _context.VolumeData.Add(data);
                _context.SaveChanges();
            });
            return RedirectToAction(nameof(Index));
        }

        public IActionResult DeleteAll()
        {
            DeleteAllDataWithoutSaving();
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }

        private void DeleteAllDataWithoutSaving()
        {
            DbSet<VolumeData> volumeData = _context.VolumeData;
            foreach (VolumeData data in volumeData)
            {
                volumeData.Remove(data);
            }
        }
    }
}

NKUST109-2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NKUST109_2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/css/my.css" />
</head>
<body class="text-white bg-dark card-dark">
    <header>
        <nav class="navbar navbar-expand-md navbar-toggleable-md navbar-dark box-shadow mb-3 border-bottom">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">NKUST109_2</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-md-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">首頁</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="VolumeData" asp-action="Index">
                                高雄輕軌月均運量統計
                            </a>
                        </li>
                        <li>
                            <a class="nav-link text-white" asp-controller="Chatroom" asp-action="Index">
                                線上聊天室
                            </a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container">
            &copy; 2021 - NKUST109_2
            <a class="float-right" href="https://github.com/Catossun/NKUST109-2">GitHub</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>